### ISSUE TITLE
Can't install this demo on windows server

### ISSUE THREAD

**Issue by fushilong** [jbossdemocentral/bpms-mortgage-demo#31]
Dear team,
I'm trying to install this demo on my windows 7 environment by running init.ps1(duo to no init.bat),and it always blocked at "Need to download jboss-eap-7.0.0-installer.jar package from the Customer support Portal and place it in the \installs directory to proceed..."  even I put these right products in \installs folder.These work fine at my linux environment by running init.sh.

I've installed all required stuff in my windows(jdk,maven,7zip,power shell) and startup with administrator privilege.

Could someone have a look? Much Appreciated!

Best Regards,
Shilong

**Comment by DuncanDoyle** [comment]
Hi,

Unfortunately I don't have a Windows 7 environment to test this out. The init.bat script was recently deprecated (basically because it didn't work and gave unexpected results) in the favour of the new init.ps1 powershell script. This script has been developed on Windows 10 and seems to work fine in that environment.

The "Need to download jboss-eap-7.0.0-installer.jar" message originates from this check: https://github.com/jbossdemocentral/bpms-mortgage-demo/blob/master/init.ps1#L54

Which basically checks whether that installer JAR is present in the "installs" directory of the project (which is determined by, among other things, this Powershell variable to determine the script-root: https://github.com/jbossdemocentral/bpms-mortgage-demo/blob/master/init.ps1#L6).

Can you give me the exact error message that you're getting? Again, as I don't have a Windows 7 environment, this is going to be hard to test, but I'll see if Windows 10 can do something like "compatibility mode".

**Comment by DuncanDoyle** [comment]
Any update on this one? Is this still an issue?

**Comment by fushilong** [comment]
Sorry for the delay,since we already used official provided demo and it works fine,so this is not a problem for us now.Thank you for your looking.
