### ISSUE TITLE
can not install demo in windows 7

### ISSUE THREAD

**Issue by sheetalkanthale** [jbossdemocentral/bpms-mortgage-demo#37]
i am trying to install demo in windows 7, but getting an issue while running init.ps1 command in powershell.
Its says, need to download jar file and put it into installs folder which i already done.

anyone pls help me on this.

**Comment by DuncanDoyle** [comment]
Are you running PowerShell version 2 or 3? There are known issues with PowerShell v2, especially around dealing with more than 260 characters on your path (which is something that happens when installing JBoss EAP with BPM Suite on top, it creates quite long path names). This is outside of my control. PowerShell v3 was released in 2012 (https://blogs.technet.microsoft.com/heyscriptingguy/2012/09/05/powershell-3-0-is-now-available-for-download/) and there is a Windows 7 version of it (https://social.technet.microsoft.com/Forums/windows/en-US/489c4c60-6bd8-41e5-bf09-3c49b694628d/upgrading-powershell-v2-to-powershell-v3-on-windows-7-64bit?forum=winserverpowershell).  Given that version 3 of PowerShell has been out for around 6 years, I've decided to deprecate PowerShell v2 support.

Can you try upgrading to PowerShell v3? If that's infeasible, you can also simply do a manual installation by simply executing the commands the script does manually (which is pretty simple actually).

Sorry for the inconvenience, it's been an ongoing problem with Windows and long paths ....
